modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="chickenhat"
version="1.0"
displayName="Chicken Hat"
authors="Slimeist"
credits="Slimeist for main code and textures, SlimeKnights for piggy back system (which is called Chickencarry in this mod), Vazkii for mob spawning systems"
description='''
Creates new uses for chickens, notably, a new type of chicken that is dyeable, and a helmet to wear such chickens on your head.
'''
license="Code, textures, and binaries are licensed under the MIT license."

[[dependencies.chickenhat]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chickenhat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chickenhat]]
modId="mantle"
mandatory=true
versionRange="[1.6.10 8,)"
ordering="NONE"
side="BOTH"
