modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="extragamerules"
version="${version}"
displayName="Extra Gamerules"
authors="Slimeist"
credits="Slimeist for code and textures"
description='''
Adds new gamerules including:
doSnowMelt - whether snow should melt in light
doIceMelt - whether ice should melt in light
zeroTickFarms - whether to re-enable zero tick farms from pre 1.16
'''
license="Code, textures, and binaries are licensed under the GNU GPL v3 license."

[[dependencies.extragamerules]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.extragamerules]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"