modLoader="javafml"
loaderVersion="[36,)"
license="All rights reserved"

[[mods]]
modId="chickenhat"
version="1.0"
displayName="Chicken Hat"
authors="Slimeist"
credits="Slimeist for main code and textures, SlimeKnights for piggy back system"
description='''
Adds a helmet that allows you to glide like a chicken
'''

[[dependencies.chickenhat]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chickenhat]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.5,1.17)"
    ordering="NONE"
    side="BOTH"

[[dependencies.chickenhat]]
modId="mantle"
mandatory=true
versionRange="[1.6.108,)"
ordering="NONE"
side="BOTH"
